apiVersion: v2
name: s3-router
description: A Helm chart for S3 Router - S3 API compatible HTTP server with flexible routing rules
type: application
version: 0.1.1
appVersion: "0.1.1"
keywords:
  - s3
  - router
  - proxy
maintainers:
  - name: s3-router
